name: ecommerce_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  flutter_native_splash: ^2.4.0  # Added ^ for version constraint
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Flutter configuration section
flutter:
  uses-material-design: true
  assets:
    - assets/image/

# Flutter native splash configuration - MUST BE AT ROOT LEVEL
flutter_native_splash:
  color: "#fffff0"
  image: assets/image/logo.jpg
  android_12:
    color: "#fffff0"
    image: assets/image/logo.jpg
  web: true